name: Flutter CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # - uses: actions/setup-java@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'


      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'

      - run: flutter pub get
      - run: flutter format --set-exit-if-changed .
      - run: flutter analyze .

      # Build release APK
      - run: flutter build apk --release

      # Upload release APK
      - uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk

      # Build debug APK
      - run: flutter build apk --debug

      # Upload debug APK
      - uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: build/app/outputs/apk/debug/app-debug.apk
